//! `macos.pasteboard`: the general pasteboard's text.
//!
//! - `readText()` -> its text, or ""
//! - `writeText(text)` -> whether it was written
//! - `watch(cb)`: `cb({ text, app, appPath })` for each text copied from now on, `app` being the
//!   frontmost app (where the copy happened) or "" for this app's own `writeText`. AppKit posts no
//!   pasteboard notifications, so a main-run-loop timer compares `changeCount` (a cheap integer
//!   read) twice a second and only reads contents when it moves. Items marked concealed or
//!   transient (password managers, per nspasteboard.org) are skipped. Returns false if already
//!   watching.

use std::cell::{Cell, RefCell};
use std::ptr::NonNull;

use block2::RcBlock;
use objc2::rc::Retained;
use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString, NSWorkspace};
use objc2_foundation::{NSString, NSTimer};
use tishlang_core::Value;

use super::{call, obj, s, str_arg};

const POLL_SECONDS: f64 = 0.5;
const MAX_CHARS: usize = 100_000;
const SKIP_TYPES: [&str; 3] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

thread_local! {
    static ON_COPY: RefCell<Option<Value>> = const { RefCell::new(None) };
    static LAST_CHANGE: Cell<isize> = const { Cell::new(-1) };
    static OWN_CHANGE: Cell<isize> = const { Cell::new(-1) };
    static TIMER: RefCell<Option<Retained<NSTimer>>> = const { RefCell::new(None) };
}

pub(super) fn read_text(_a: &[Value]) -> Value {
    s(&NSPasteboard::generalPasteboard()
        .stringForType(unsafe { NSPasteboardTypeString })
        .map(|t| t.to_string())
        .unwrap_or_default())
}

pub(super) fn write_text(args: &[Value]) -> Value {
    let pb = NSPasteboard::generalPasteboard();
    pb.clearContents();
    let ok = pb.setString_forType(&NSString::from_str(&str_arg(args, 0)), unsafe {
        NSPasteboardTypeString
    });
    OWN_CHANGE.with(|c| c.set(pb.changeCount()));
    Value::Bool(ok)
}

pub(super) fn watch(args: &[Value]) -> Value {
    if TIMER.with(|t| t.borrow().is_some()) {
        return Value::Bool(false);
    }
    ON_COPY.with(|c| *c.borrow_mut() = args.first().cloned());
    LAST_CHANGE.with(|c| c.set(NSPasteboard::generalPasteboard().changeCount()));
    let block = RcBlock::new(|_t: NonNull<NSTimer>| poll());
    let timer = unsafe {
        NSTimer::scheduledTimerWithTimeInterval_repeats_block(POLL_SECONDS, true, &block)
    };
    // A copy overwritten before the next poll is lost, so keep the gap close to POLL_SECONDS.
    timer.setTolerance(0.1);
    TIMER.with(|t| *t.borrow_mut() = Some(timer));
    Value::Bool(true)
}

fn poll() {
    let pb = NSPasteboard::generalPasteboard();
    let change = pb.changeCount();
    if LAST_CHANGE.with(|c| c.replace(change)) == change {
        return;
    }
    let skip = pb.types().is_some_and(|ts| {
        (0..ts.count()).any(|i| SKIP_TYPES.contains(&ts.objectAtIndex(i).to_string().as_str()))
    });
    if skip {
        return;
    }
    let Some(t) = pb.stringForType(unsafe { NSPasteboardTypeString }) else {
        return;
    };
    let mut text = t.to_string();
    if text.trim().is_empty() {
        return;
    }
    if text.len() > MAX_CHARS {
        let mut cut = MAX_CHARS;
        while !text.is_char_boundary(cut) {
            cut -= 1;
        }
        text.truncate(cut);
    }
    let (app, app_path) = if OWN_CHANGE.with(|c| c.get()) == change {
        (String::new(), String::new())
    } else {
        frontmost()
    };
    let Some(cb) = ON_COPY.with(|c| c.borrow().clone()) else {
        return;
    };
    call(
        &cb,
        &[obj(vec![
            ("text", s(&text)),
            ("app", s(&app)),
            ("appPath", s(&app_path)),
        ])],
    );
}

/// This app never takes focus from a copy, so the frontmost app is where it happened.
fn frontmost() -> (String, String) {
    let Some(a) = NSWorkspace::sharedWorkspace().frontmostApplication() else {
        return (String::new(), String::new());
    };
    let name = a.localizedName().map(|n| n.to_string()).unwrap_or_default();
    let path = a
        .bundleURL()
        .and_then(|u| u.path())
        .map(|p| p.to_string())
        .unwrap_or_default();
    (name, path)
}
